/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class gameUI extends Laya.Scene {
		public bg:Laya.Sprite;
		public timu:Laya.Label;
		public ansbox:Laya.Box;
		public ans1:Laya.Image;
		public num1:Laya.Label;
		public ans2:Laya.Image;
		public num2:Laya.Label;
		public ans3:Laya.Image;
		public num3:Laya.Label;
		public ans4:Laya.Image;
		public num4:Laya.Label;
		public tip:Laya.Image;
		public tiplab:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/game");
        }
    }
    REG("ui.test.gameUI",gameUI);
}